lab5_3/apps/authentication_form/urls.py
from django.urls import path

from . import views

app_name = 'main_form'
urlpatterns = [
    path('', views.index, name='index'),
]

lab5_3/apps/root/urls.py
from django.urls import path

from . import views

app_name = 'root'
urlpatterns = [
    path('', views.show_tables, name='show_tables'),
    path('table/', views.show_table, name='show_table'),
    path('table_backup/', views.show_table_old, name='show_table_old'),
    path('db_dumps/', views.show_dumps, name='show_dumps'),
    path('enter_table/', views.enter_table, name='enter_table'),
    path('back_num/', views.back_num, name='back_num'),
]

lab5_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('authentication_form.urls')),
    path('root/', include('root.urls')),
    path('admin/', admin.site.urls),
]

lab5_3/apps/authentication_form/models.py
from django.db import models

# Create your models here.

lab5_3/apps/root/models.py
from django.db import models

# Create your models here.

lab5_3/apps/authentication_form/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from lab5_3.apps import DB

scripts = None

def index(request):
    if 'login' in request.POST and 'password' in request.POST:
        DB.a = DB.DB(request.POST['login'], request.POST['password'], )
        if DB.a.login:
            return HttpResponseRedirect(reverse('root:show_tables'))
        DB.scripts = 'wrong password or login'
        return HttpResponseRedirect(reverse('main_form:index'))
    return render(request, 'authentication_form/main_form.html', {'scripts': DB.scripts})

lab5_3/apps/root/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.db import transaction
from lab5_3.apps import DB


def show_tables(request):
    if DB.a.login:
        return render(request, 'root/main_root.html', {'tables': DB.a.get_tables()})
    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))


def show_components(request):
    if DB.a.login and DB.a.lvl == 3 or DB.a.login and DB.a.lvl == 2 or DB.a.login and DB.a.lvl == 0:
        save = DB.scripts
        DB.scripts = None
        link = 'http://127.0.0.1:8000/root/enter_components/'
        link2 = 'http://127.0.0.1:8000/root/enter_components_s/'
        return render(request, 'root/show_table.html',
                      {'tittles': DB.a.show_components()[0], 'strings': DB.a.show_components()[1:], 'link': link,
                       'link2': link2, 'last': DB.a.show_components()[-1], 'scripts': save})
    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

def show_table_old(request):
    if DB.a.login and DB.a.lvl == 3 or DB.a.login and DB.a.lvl == 2 or DB.a.login and DB.a.lvl == 0:
        save = DB.scripts
        DB.scripts = None
        if 'table' in request.POST:
            DB.link = request.POST['table']
        if 'link' in request.POST:
            link = request.POST['link']
        else:
            link = DB.link
            DB.link = None
        DB.link = link
        if '_apply' in request.POST:
            if request.POST['operation'] == 'INSERT':
                DB.a.del_string(request.POST['id'], request.POST['table'])
            elif request.POST['operation'] == 'DELETE':
                mass = []
                m = DB.a.output_titles(request.POST['table'])
                for i in request.POST:
                    if i in m:
                        mass.append(request.POST[i])
                DB.a.insert(mass, request.POST['table'])
            elif request.POST['operation'] == 'UPDATE':
                mass = []
                m = DB.a.output_titles(request.POST['table'])
                for i in request.POST:
                    if i in m:
                        mass.append(request.POST[i])
                mass.append(request.POST['id'])
                DB.a.update(mass, request.POST['table'])
            return HttpResponseRedirect(reverse('root:show_table'))
        else:
            return render(request, 'root/backups.html',
                          {'tables': DB.a.get_tables(),
                           'table': link,
                           'titles': DB.a.output_titles('{}_old'.format(link)),
                           'strings': DB.a.output_tables('{}_old'.format(link)), 'scripts': save})
    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

def show_dumps(request):
    if DB.a.login and DB.a.lvl == 3 or DB.a.login and DB.a.lvl == 2 or DB.a.login and DB.a.lvl == 0:
        save = DB.scripts
        DB.scripts = None
        if 'table' in request.POST:
            DB.link = request.POST['table']
        if 'link' in request.POST:
            link = request.POST['link']
        else:
            link = DB.link
            DB.link = None
        DB.link = link
        if '_create_dumps' in request.POST:
            DB.crt_brack_on_start()
            return HttpResponseRedirect(reverse('root:show_dumps'))
        elif '_restore' in request.POST:
            del DB.a
            DB.restore_db(request.POST['dump'])
            DB.a = DB.DB('admin', 'admin')
            return HttpResponseRedirect(reverse('root:show_dumps'))
        else:
            return render(request, 'root/dumps.html',
                          {'strings': DB.watch_dir()})
    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

def show_table(request):
    if DB.a.login:
        save = DB.scripts
        DB.scripts = None
        if 'table' in request.POST:
            DB.link = request.POST['table']
        if DB.a.lvl == 3 or DB.a.lvl == 0 or DB.a.lvl == 2:
            if '_del' in request.POST:
                DB.a.del_string(request.POST['id_old'], request.POST['table'])
            elif '_edit' in request.POST:
                mass = []
                m = DB.a.output_titles(DB.link)
                for i in request.POST:
                    if i in m:
                        mass.append(request.POST[i])
                mass.append(request.POST['id_old'])
                try:
                    DB.a.update(mass, DB.link)
                except:
                    DB.a.rollback()
                    DB.scripts = 'incorrect input'
            elif '_add' in request.POST:
                try:
                    mass = []
                    m = DB.a.output_titles(DB.link)
                    for i in request.POST:
                        if i in m:
                            mass.append(request.POST[i])
                    DB.a.insert(mass, DB.link)
                except Exception as e:
                    print(e)
                    DB.a.rollback()
                    DB.scripts = 'incorrect input'

        if 'link' in request.POST:
            link = request.POST['link']
        else:
            link = DB.link
            DB.link = None
        if DB.a.output_tables(link):
            last = DB.a.output_tables(link)[-1]
        else:
            last = None
        if '_search' in request.POST:
            DB.link = link
            mass = []
            m = DB.a.output_titles(DB.link)
            for i in request.POST:
                if i in m:
                    mass.append(request.POST[i])

            return render(request, 'root/show_table.html', {
                'tables': DB.a.get_tables(),
                'table': link,
                'titles': DB.a.output_titles(link),
                'strings': DB.a.search_component(request.POST['table'], mass),
                'last': last,
                'scripts': save
            })
        else:
            DB.link = link
            return render(request, 'root/show_table.html',
                          {'tables': DB.a.get_tables(),
                           'table': link,
                           'titles': DB.a.output_titles(link),
                           'last': last,
                           'strings': DB.a.output_tables(link), 'scripts': save})
    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

def enter_table(request):
    if DB.a.login and DB.a.lvl == 3 or DB.a.login and DB.a.lvl == 2 or DB.a.login and DB.a.lvl == 0:

        return HttpResponseRedirect(reverse('root:show_table'))

    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

def back_num(request):
    if DB.a.login and DB.a.lvl == 3 or DB.a.login and DB.a.lvl == 2 or DB.a.login and DB.a.lvl == 0:
        DB.a.back_num(request.POST['num'], request.POST['table'])
        return HttpResponseRedirect(reverse('root:show_table'))

    DB.scripts = 'wrong password or login'
    return HttpResponseRedirect(reverse('main_form:index'))

lab5_3/templates/authentication_form/main_form.html
{% extends 'base.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'authentication_form/style.css' %}">
{% endblock %}
{% block title %}Аутентификация{% endblock %}

{% block content %}

    <form action="{% url 'main_form:index'%}" method="POST">

        {% csrf_token %}

        <div class="main_form">
            <div class="input-group">
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text change_size_form fix_padding_main_form" id="inputGroup-sizing-default">Логин</span>
                    </div>
                    <input type="text" name="login" class="form-control" aria-label="Default"
                           aria-describedby="inputGroup-sizing-default">
                </div>
                <div class="input-group mb-1">
                    <div class="input-group-prepend">
                        <span class="input-group-text change_size_form" id="inputGroup-sizing-default">Пароль</span>
                    </div>
                    <input type="password" name="password" class="form-control" aria-label="Default"
                           aria-describedby="inputGroup-sizing-default">
                </div>
            </div>
            <button type="sumbit" class="btn btn-success button_center">Войти</button>
        </div>



    </form>
{% endblock %}
{% block scripts %}
    {% if scripts == 'wrong password or login' %}
        <script>
            alert('{{ scripts }}');
        </script>
    {% endif %}
{% endblock %}

lab5_3/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block static %}{% endblock %}
</head>
<body>

    {% block content %}{% endblock %}
    {% block scripts %}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

lab5_3/templates/root/backups.html
{% extends 'root/main_root.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'root/style.css' %}">
{% endblock %}
{% block title %}{{ tittle }}{% endblock %}

{% block tables %}

    <div style="position: absolute; top: 0px; left: 5px;">
        <form action="{% url 'root:show_table' %}" method="POST">
            {% csrf_token %}
            <div>
                <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                <input type="submit" class="btn btn-primary" name="_back" value="back">
            </div>
        </form>
    </div>

    <div style="display: flex; align-items: center; justify-content: center">

        <table class="table table-inverse">
            <thead>
            <tr>
                {% for i in titles %}
                    <th>{{ i }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
                {% for string in strings %}
                    <tr>
                        <form action="{% url 'root:show_table_old' %}" method="POST" class="dn" style="display: none">
                            {% csrf_token %}
                            {% for i, j in string %}
                                {% if j|length > 0 %}
                                    <td>
                                        <input type="text" name="{{ i }}" class="form-control-plaintext"
                                               value="{{ j }}">
                                    </td>
                                {% else %}
                                    <td style="width: 80px">
                                        <input type="text" name="{{ i }}" class="form-control-plaintext" size="2"
                                               value="{{ j }}">
                                    </td>
                                {% endif %}
                            {% endfor %}
                            <td>
                                <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                                <input type="submit" class="btn btn-primary" name="_apply" value="Apply">
                            </td>
                        </form>
                    </tr>
                {% endfor %}
            </tbody>
            {#  <tr>#}
            {#    <form action="{% url 'root:back_num' %}" method="POST">#}
            {#        {% csrf_token %}#}
            {#        <td>#}
            {#            <input type="text" name="num" class="form-control-plaintext">#}
            {#            <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">#}
            {#            <input type="submit" class="btn btn-primary" name="a" value="back">#}
            {#        </td>#}
            {#    </form>#}
            {#</tr>#}
        </table>
    </div>
{% endblock %}

{% block scripts %}
    {% if scripts == 'incorrect input' %}
        <script>
            alert('{{ scripts }}');
        </script>
    {% endif %}
{% endblock %}

lab5_3/templates/root/dumps.html
{% extends 'root/main_root.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'root/style.css' %}">
{% endblock %}
{% block title %}{{ tittle }}{% endblock %}

{% block tables %}

    <div style="position: absolute; top: 0px; right: 85px;">
        <form action="{% url 'root:show_table' %}" method="POST">
            {% csrf_token %}
            <div>
                <input type="submit" class="btn btn-primary" name="_back" value="back">
            </div>
        </form>
    </div>

    <div style="position: absolute; top: 0; right: 5px;">
        <form action="{% url 'root:show_dumps' %}" method="POST">
            {% csrf_token %}
            <div>
                <input type="submit" class="btn btn-danger" name="_create_dumps" value="Dump">
            </div>
        </form>
    </div>

    <div style="display: flex; align-items: center; justify-content: center">

        <table class="table table-inverse">
            <thead>
            <tr>
                <th>Dump name</th>
                <th>Dump date</th>
            </tr>
            </thead>
            <tbody>
                {% for i, j in strings %}
                    <tr>
                        <form action="{% url 'root:show_dumps' %}" method="POST" class="dn" style="display: none">
                            {% csrf_token %}
                            <td>
                                <input type="text" name="dump" class="form-control-plaintext"
                                       value="{{ i }}">
                            </td>
                            <td>
                                <input type="text" name="date" class="form-control-plaintext"
                                       value="{{ j }}">
                            </td>
                            <td>
                                <input type="submit" class="btn btn-primary" name="_restore" value="Recovery">
                            </td>
                        </form>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block scripts %}
    {% if scripts == 'incorrect input' %}
        <script>
            alert('{{ scripts }}');
        </script>
    {% endif %}
{% endblock %}

lab5_3/templates/root/main_root.html
{% extends 'base.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'root/style.css' %}">
{% endblock %}
{% block title %}Root{% endblock %}

{% block content %}
    <div class="btn-group" role="group" style="display: flex; align-items: center; justify-content: center" aria-label="Basic example">
        <form action="{% url 'root:show_table' %}"  method="POST">
            {% csrf_token %}
            {% for i in tables %}
                <input type="submit" class="btn btn-secondary" name="link" value="{{ i }}">
            {% endfor %}
        </form>
    </div>
    {% block tables %}

    {% endblock %}

{% endblock %}

lab5_3/templates/root/show_table.html
{% extends 'root/main_root.html' %}
{% block static %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'root/style.css' %}">
{% endblock %}
{% block title %}{{ tittle }}{% endblock %}

{% block tables %}

    <div style="position: absolute; top: 0; right: 5px;">
        <form action="{% url 'root:show_table_old' %}" method="POST">
            {% csrf_token %}
            <div>
                <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                <input type="submit" class="btn btn-danger" name="_backup" value="Backup">
            </div>
        </form>
    </div>

    <div style="position: absolute; top: 0; right: 85px;">
        <form action="{% url 'root:show_dumps' %}" method="POST">
            {% csrf_token %}
            <div>
                <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                <input type="submit" class="btn btn-danger" name="_dump" value="Dumps">
            </div>
        </form>
    </div>

    <div style="display: flex; align-items: center; justify-content: center">

        <table class="table table-inverse">
            <thead>
            <tr>
                {% for i in titles %}
                    <th>{{ i }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% if strings %}
                {% for string in strings %}
                    <tr>
                        <form action="{% url 'root:show_table' %}" method="POST" class="dn" style="display: none">
                            {% csrf_token %}
                            {% for i, j in string %}
                                {% if j|length > 0 %}
                                    <td>
                                        <input type="text" name="{{ i }}" class="form-control-plaintext"
                                               value="{{ j }}">
                                        <input type="hidden" name="{{ i }}_old" id="exampleInputPassword1"
                                               value="{{ j }}">
                                    </td>
                                {% else %}
                                    <td style="width: 120px">
                                        <input type="text" name="{{ i }}" class="form-control-plaintext" size="2"
                                               value="{{ j }}">
                                        <input type="hidden" name="{{ i }}_old" id="exampleInputPassword1"
                                               value="{{ j }}">
                                    </td>
                                {% endif %}
                            {% endfor %}
                            <td>
                                <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                                <input type="submit" class="btn btn-primary" name="_edit" value="Change">
                                <input type="submit" class="btn btn-danger" name="_del" value="Delete">
                            </td>
                        </form>
                    </tr>
                {% endfor %}
                <tr>
                    <form action="{% url 'root:show_table' %}" method="POST" class="dn" style="display: none">
                        {% csrf_token %}
                        {% for i, j in last %}
                            {% if j|length > 0 %}
                                <td>
                                    <input type="text" name="{{ i }}" class="form-control" id="exampleInputPassword1"
                                           placeholder="{{ i }}">
                                    <input type="hidden" name="{{ i }}_old" id="exampleInputPassword1" value="{{ i }}">
                                </td>
                            {% else %}
                                <td>
                                    <input type="text" name="{{ i }}" class="form-control" id="exampleInputPassword1"
                                           size="2" placeholder="{{ i }}">
                                    <input type="hidden" name="{{ i }}_old" id="exampleInputPassword1" value="{{ i }}">
                                </td>
                            {% endif %}

                        {% endfor %}
                        <td>
                            <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                            <input type="submit" class="btn btn-primary" name="_add" value="Add">
                            <input type="submit" class="btn btn-primary" name="_search" value="Search">
                        </td>
                    </form>
                </tr>
            {% else %}
                <tr>
                    <form action="{% url 'root:show_table' %}" method="POST" class="dn" style="display: none">
                        {% csrf_token %}
                        {% for i in titles %}
                            <td>
                                <input type="text" name="{{ i }}" class="form-control" id="exampleInputPassword1"
                                       placeholder="{{ i }}">
                                <input type="hidden" name="{{ i }}_old" id="exampleInputPassword1" value="{{ i }}">
                            </td>
                        {% endfor %}
                        <td>
                            <input type="hidden" name="table" id="exampleInputPassword1" value="{{ table }}">
                            <input type="submit" class="btn btn-primary" name="_add" value="Add">
                            <input type="submit" class="btn btn-primary" name="_search" value="Search">
                        </td>
                    </form>
                </tr>
            {% endif %}
            </tbody>
        </table>

    </div>




{% endblock %}

{% block scripts %}
    {% if scripts == 'incorrect input' %}
        <script>
            alert('{{ scripts }}');
        </script>
    {% endif %}
{% endblock %}